// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5pneFkpnhOxAux1C4NwUSoCQMlVqCBQ',
    appId: '1:762462380120:android:948f622aca5d9281f1aa2d',
    messagingSenderId: '762462380120',
    projectId: 'tiktok-clone-f4a8b',
    storageBucket: 'tiktok-clone-f4a8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnHfbE74QoUG14QpTf5m_QnhnkqbN5Sw',
    appId: '1:762462380120:ios:c5ecab15ed77f2ccf1aa2d',
    messagingSenderId: '762462380120',
    projectId: 'tiktok-clone-f4a8b',
    storageBucket: 'tiktok-clone-f4a8b.appspot.com',
    iosClientId: '762462380120-gee42rrhocqiftl6tigcpmvkk9q2nfbm.apps.googleusercontent.com',
    iosBundleId: 'com.husamdahliz.tiktokClone',
  );
}
